Card detail page
Hyperskill-Community/flashcards pull request #61
Opened 2024-01-29 17:18 UTC by Averageasd

finished card detail. Print out error message if card with id is not available.

2024-01-29 18:01 UTC, wisskirchenj commented
general comments:
1) Add the options for this card- if you give answer 3 - user needs to see, which 4 options are given... (ordered list - try to find a vuetify component [v-list)](https://vuetifyjs.com/en/components/lists/)
2) use edit and delete from shared/components - see CategoryCard.vue and place them same way as there -> might be that we place them below later (Victors comment) - but for now I would use same style as this page has
3) same for color - use the lightblue of CategoryOverview (I will later create SASS-variables $primary etc. to make sure, the colors are same - and easy replaceable).  
(for same consistent look reason: pls do not use excessive css. stick to the defaults and if not, we must change this globally (exceptions may occur))
4) Delete the id in the page title - it was just for start reasons, to see, that it gets to the page.

2024-01-29 19:34 UTC, Averageasd commented
ok just made necessary changes

2024-01-29 19:42 UTC, wisskirchenj requested changes

2024-01-29 19:42 UTC, wisskirchenj commented on .dev/http-client/get-cards.http
generally, better do not commit these files, if only you change the id... but it's ok for this PR...

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +    class="pa-2 ma-2 mx-auto d-flex flex-column justify-space-between" max-width="500px" min-height="300px">
i would not use pixel width or heights, the usual way is to use the columns classes like v-col-sm-4. tailwind divides the parent component into 12 cols. and you can provide v-col-sm1 to v-col-sm-12 to define relative width - similar for heights but rarely used.

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +      {{ card.title }}
iw ould drop class text-center and insert v-card-title with buttons, like this (replacing texts of course...):
```html
    <v-card-title class="d-flex justify-space-between align-center">
      <h4>{{ category.name }}</h4>
      <div class="mr-n6">
        <edit-mdi-button tooltip-text="Rename Category"
                         :disabled="!putUri"
                         :clickHandler="editCategory"/>
        <delete-mdi-button tooltip-text="Delete Category"
                           :disabled="!deleteUri"
                           :clickHandler="deleteCategory"/>
      </div>
    </v-card-title>
``´

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +          </template>
you do not need the index here, v-for just goes over all tags.
AND the use of this generic template tag makes no sense here. for a generic container use v-container or just div or span (depending if you want block or inline element)

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +          </template>
also: the tags are no subtitle: moven them in text part. and write label "tags" in front of them

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +    </v-card-text>
Question should have label question in front,
then (the missing) options and correct option

=> Provide to each card detail data you display **also the field**, describing which data these are

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +  </v-card>
these buttons are replaced by the ones in title - see above

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +
try to not use css here - you can achieve the tag separation with tailwind classes - makes sense to learn more and more of them :-)
Of course exceptionally, css is OK.

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/pages/CardDetailsPage.vue
> +
just
```
const card = ref<Card>({});
```

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/pages/CardDetailsPage.vue
> +const error = ref(null);
remove this error variable

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/composables/useCardsService.ts
> +      return null;
use `return {} as Card;`- avoid null if possible...

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +      <p>
you use display none in css and then you create your index wourself ?!?

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/composables/useCardsService.ts
> +  const getCardById = async (cardId: string, categoryId: string, errorResult: string = 'throw'): Promise<Card | null> => {
return type is Promise<Card> with changes below

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +      </v-card-actions>
no text in the buttons :-( we have tooltips - see code below. also move them into v-card-title

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetailsComponent.vue
> +
we use the more modern defineProps generic approach with TS:
here this would be just 
```typescript
defineProps<({
  card: Card
})>();
```

2024-01-29 19:42 UTC, wisskirchenj commented on frontend/src/feature/cards/pages/CardDetailsPage.vue
> +}
no error handling here! This is done in composable.
just 
```
async function fetchCardWithId() {
    card.value = await useCardsService().getCardById(props.id!, CATEGORY_ID);
}
```

2024-02-03 20:49 UTC, wisskirchenj approved these changes

2024-02-03 21:23 UTC, merged