finished delete card functionality. After the operation was done, car…
Hyperskill-Community/flashcards pull request #92
Opened 2024-03-18 14:48 UTC by Averageasd

…d scroller was displayed.

2024-03-18 21:32 UTC, wisskirchenj commented on frontend/src/feature/cards/components/CardDetails.vue
> +      <delete-mdi-button :click-handler="() => emit('delete', card)"/>
Pls add tooltipText property - for convenience, they are on all the buttons:
`tooltip-text="Delete Card"` is sufficient

2024-03-18 22:18 UTC, wisskirchenj requested changes
https://github.com/Hyperskill-Community/flashcards/pull/92#discussion_r1529311130

2024-03-19 00:21 UTC, Averageasd commented
Added tooltiptext to delete card button.

2024-03-19 06:58 UTC, wisskirchenj approved these changes

2024-03-20 00:04 UTC, merged